% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Bellabeat},
  pdfauthor={Marisa Kuyava},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Bellabeat}
\author{Marisa Kuyava}
\date{}

\begin{document}
\maketitle

\subsection{\texorpdfstring{\textbf{How can a wellness company play it
smart?}}{How can a wellness company play it smart?}}\label{how-can-a-wellness-company-play-it-smart}

\subsubsection{\texorpdfstring{\textbf{1.
Introduction}}{1. Introduction}}\label{introduction}

\paragraph{\texorpdfstring{\textbf{Company}}{Company}}\label{company}

\href{https://bellabeat.com/}{Bellabeat}

\begin{itemize}
\tightlist
\item
  Bellabeat develops beautifully designed, high-tech, health-focused
  smart products for women.
\end{itemize}

\subparagraph{\texorpdfstring{\textbf{Stakeholders}}{Stakeholders}}\label{stakeholders}

\begin{itemize}
\tightlist
\item
  Urška Sršen: Chief Creative Officer and Bellabeat Cofounder
\item
  Sando Mu: Key member of executive team and Bellabeat Cofounder
\item
  The Bellabeat Marketing Analytics team: Responsible for collecting,
  analyzing, and reporting data
\end{itemize}

\subsubsection{\texorpdfstring{\textbf{2. Ask}}{2. Ask}}\label{ask}

\subparagraph{\texorpdfstring{\textbf{Scenario}}{Scenario}}\label{scenario}

As a data analyst on the Bellabeat marketing analyst team I have been
tasked with analyzing public smart device data to gain insight into how
smart devices are being used by consumers.

\subparagraph{\texorpdfstring{\textbf{Goal}}{Goal}}\label{goal}

Provide insights on trends in smart device usage that will help unlock
new growth opportunities for the company and help guide marketing
strategies.

\subsubsection{\texorpdfstring{\textbf{3.
Prepare}}{3. Prepare}}\label{prepare}

\subparagraph{Libraries Utilized:}\label{libraries-utilized}

\begin{itemize}
\tightlist
\item
  tidyverse
\item
  dplyr
\item
  here
\item
  janitor
\item
  lubridate
\item
  skimr
\item
  ggplot2
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Data}}{Data}}\label{data}

\textbf{Storage and Accessibility}\\

The data set being analyzed is
\href{https://www.kaggle.com/datasets/arashnic/fitbit}{FitBit Fitness
Tracker Data} provided on \href{https://www.kaggle.com}{Kaggle}. The
data set was generated by thirty eligible FitBit user respondents, to a
distributed survey via Amazon Mechanical Turn, between the dates of
April 12, 2016 and May 12, 2016. These users consented to the submission
of personal tracker data, including minute-level output for physical
activity, heart rate, and sleep monitoring.

\textbf{Organization and ROCCC}\\

\begin{itemize}
\tightlist
\item
  The data is provided in 18 CSV files, after reviewing the data it was
  determined that the data in the files imported below contain the most
  complete and relevant data. The data was cleaned, including checking
  for duplicate files, and formats were standardized to ensure
  completeness and accuracy.
\item
  The data set is obsolete for analyzing current trends as it was
  gathered in 2016.
\item
  Data set sample size is limited to 30 individuals; this is the
  smallest sample size possible to be statistically in representing the
  population. A larger sample size would provide a higher confidence
  level, a decrease margin of error and a greater statistical
  significance.
\item
  Data is possibly not relevant for the customers Bellabeat targeted
  audience as the data provided does not provide user respondents
  gender.
\item
  Some data provided was manually entered and could contain error of be
  incorrect information.
\end{itemize}

\textbf{Variables Measured}\\

\begin{itemize}
\tightlist
\item
  Steps
\item
  Sleep
\item
  Calories
\item
  Intensity
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Data
Import}}{Data Import}}\label{data-import}

\begin{itemize}
\tightlist
\item
  6 of 18 files will be used as data provided in the other files are a
  duplication.
\item
  Data was imported and each file was confirmed as successfuly uploaded.
\end{itemize}

\textbf{Daily Activity}

\begin{verbatim}
## 'data.frame':    940 obs. of  15 variables:
##  $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
##  $ ActivityDate            : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
##  $ TotalSteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
##  $ TotalDistance           : num  8.5 6.97 6.74 6.28 8.16 ...
##  $ TrackerDistance         : num  8.5 6.97 6.74 6.28 8.16 ...
##  $ LoggedActivitiesDistance: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...
##  $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
##  $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
##  $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
##  $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
##  $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
##  $ SedentaryMinutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
##  $ Calories                : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...
\end{verbatim}

\textbf{Daily Sleep}

\begin{verbatim}
## 'data.frame':    413 obs. of  5 variables:
##  $ Id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
##  $ SleepDay          : chr  "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
##  $ TotalSleepRecords : int  1 2 1 2 1 1 1 1 1 1 ...
##  $ TotalMinutesAsleep: int  327 384 412 340 700 304 360 325 361 430 ...
##  $ TotalTimeInBed    : int  346 407 442 367 712 320 377 364 384 449 ...
\end{verbatim}

\textbf{Hourly Calories}

\begin{verbatim}
## 'data.frame':    22099 obs. of  3 variables:
##  $ Id          : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
##  $ ActivityHour: chr  "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
##  $ Calories    : int  81 61 59 47 48 48 48 47 68 141 ...
\end{verbatim}

\textbf{Hourly Intensity}

\begin{verbatim}
## 'data.frame':    22099 obs. of  4 variables:
##  $ Id              : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
##  $ ActivityHour    : chr  "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
##  $ TotalIntensity  : int  20 8 7 0 0 0 0 0 13 30 ...
##  $ AverageIntensity: num  0.333 0.133 0.117 0 0 ...
\end{verbatim}

\textbf{Hourly Steps}

\begin{verbatim}
## 'data.frame':    22099 obs. of  3 variables:
##  $ Id          : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
##  $ ActivityHour: chr  "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
##  $ StepTotal   : int  373 160 151 0 0 0 0 0 250 1864 ...
\end{verbatim}

\textbf{Weight}

\begin{verbatim}
## 'data.frame':    67 obs. of  8 variables:
##  $ Id            : num  1.50e+09 1.50e+09 1.93e+09 2.87e+09 2.87e+09 ...
##  $ Date          : chr  "5/2/2016 11:59:59 PM" "5/3/2016 11:59:59 PM" "4/13/2016 1:08:52 AM" "4/21/2016 11:59:59 PM" ...
##  $ WeightKg      : num  52.6 52.6 133.5 56.7 57.3 ...
##  $ WeightPounds  : num  116 116 294 125 126 ...
##  $ Fat           : int  22 NA NA NA NA 25 NA NA NA NA ...
##  $ BMI           : num  22.6 22.6 47.5 21.5 21.7 ...
##  $ IsManualReport: chr  "True" "True" "False" "True" ...
##  $ LogId         : num  1.46e+12 1.46e+12 1.46e+12 1.46e+12 1.46e+12 ...
\end{verbatim}

\subsubsection{\texorpdfstring{\textbf{4.
Process}}{4. Process}}\label{process}

\paragraph{\texorpdfstring{\textbf{Data
Cleaning}}{Data Cleaning}}\label{data-cleaning}

\begin{itemize}
\tightlist
\item
  Data set was checked for duplicates and missing values.
\item
  Duplicate data was removed from the dataset
\item
  Dates and date column name within the data set were all normalized
\item
  Individual files were merged for easier analysis
\end{itemize}

\subsubsection{\texorpdfstring{\textbf{5.
Analyze}}{5. Analyze}}\label{analyze}

\paragraph{\texorpdfstring{\textbf{Data
Analysis}}{Data Analysis}}\label{data-analysis}

\textbf{Data Summary - Distances}

\begin{verbatim}
##   Steps_Total    Distance_Total   High_Activity     Mid_Activity   
##  Min.   :   17   Min.   : 0.010   Min.   : 0.000   Min.   :0.0000  
##  1st Qu.: 5189   1st Qu.: 3.592   1st Qu.: 0.000   1st Qu.:0.0000  
##  Median : 8913   Median : 6.270   Median : 0.570   Median :0.4200  
##  Mean   : 8515   Mean   : 6.012   Mean   : 1.446   Mean   :0.7439  
##  3rd Qu.:11370   3rd Qu.: 8.005   3rd Qu.: 2.360   3rd Qu.:1.0375  
##  Max.   :22770   Max.   :17.540   Max.   :12.540   Max.   :6.4800  
##   Low_Activity  
##  Min.   :0.010  
##  1st Qu.:2.540  
##  Median :3.665  
##  Mean   :3.791  
##  3rd Qu.:4.918  
##  Max.   :9.480
\end{verbatim}

\textbf{Standard Deviations - Distances}

\begin{verbatim}
## [1] "Steps_Total:              4157.3756"
\end{verbatim}

\begin{verbatim}
## [1] "Distance_Total:           3.0439"
\end{verbatim}

\begin{verbatim}
## [1] "High_Activity_Distance:   1.9926"
\end{verbatim}

\begin{verbatim}
## [1] "Mid_Activity_Distance:    0.9998"
\end{verbatim}

\begin{verbatim}
## [1] "Low_Activity_Distance:    1.7208"
\end{verbatim}

\textbf{Data Summary - Time}

\begin{verbatim}
##  High_Active_Min  Mid_Activive_Min Low_Activive_Min Sedentary_Min   
##  Min.   :  0.00   Min.   :  0.00   Min.   :  2.0    Min.   :   0.0  
##  1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:158.0    1st Qu.: 631.2  
##  Median :  9.00   Median : 11.00   Median :208.0    Median : 717.0  
##  Mean   : 25.05   Mean   : 17.92   Mean   :216.5    Mean   : 712.1  
##  3rd Qu.: 38.00   3rd Qu.: 26.75   3rd Qu.:263.0    3rd Qu.: 782.8  
##  Max.   :210.00   Max.   :143.00   Max.   :518.0    Max.   :1265.0  
##    Asleep_Min      InBed_Min        Calorie    
##  Min.   : 58.0   Min.   : 61.0   Min.   : 257  
##  1st Qu.:361.0   1st Qu.:403.8   1st Qu.:1841  
##  Median :432.5   Median :463.0   Median :2207  
##  Mean   :419.2   Mean   :458.5   Mean   :2389  
##  3rd Qu.:490.0   3rd Qu.:526.0   3rd Qu.:2920  
##  Max.   :796.0   Max.   :961.0   Max.   :4900
\end{verbatim}

\textbf{Standard Deviations - Time}

\begin{verbatim}
## [1] "High_Activity_Minutes:   36.2182"
\end{verbatim}

\begin{verbatim}
## [1] "Mid_Activity_Minutes:    22.4186"
\end{verbatim}

\begin{verbatim}
## [1] "Low_Activity_Minutes:    86.7053"
\end{verbatim}

\begin{verbatim}
## [1] "Sedentary_Minutes:       166.1794"
\end{verbatim}

\begin{verbatim}
## [1] "Asleep_Minutes:          118.6359"
\end{verbatim}

\begin{verbatim}
## [1] "InBed_Minutes:           127.4551"
\end{verbatim}

\begin{verbatim}
## [1] "Calories Burned:         758.435"
\end{verbatim}

\textbf{Observations from statistical Summary}\\

\begin{itemize}
\tightlist
\item
  Users average a distance of 6.27 miles and 8515 steps daily
\item
  There is a significant variation between users activity as the
  standard deviation for distance is 3 and for steps is 4157
\item
  Users spend the most time doing Low activity, this correlates with low
  activity distance being the greatest
\item
  Users burn an average of 2389 calories per day
\item
  Users average sleep time is 6.98 hours with time in bed at 7.65 hours
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Activity
Summary}}{Activity Summary}}\label{activity-summary}

\begin{verbatim}
##            Count Percentage                             Steps
## Low Steps     96   23.41463                    Less than 5000
## Mid Steps    149   36.34146 More than 5000 and Less than 1000
## High Steps   165   40.24390       Equal or Greater than 10000
\end{verbatim}

\textbf{Observations from Activity Summary}

\begin{itemize}
\tightlist
\item
  The majority of users have mid to high activity at 76\%
\item
  40\% reaching the recommended 10K steps per day
\item
  23\% of users are well below the recommended 10K steps per day
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Sleep
Correlations}}{Sleep Correlations}}\label{sleep-correlations}

\begin{verbatim}
##                      Correlation of Minutes Asleep
## TotalSteps                             -0.19034392
## TotalDistance                          -0.17693625
## VeryActiveMinutes                      -0.08812658
## FairlyActiveMinutes                    -0.24920793
## LightlyActiveMinutes                    0.02758336
## SedentaryMinutes                       -0.60107314
## Calories                               -0.03169899
## TotalMinutesAsleep                      1.00000000
## TotalTimeInBed                          0.93042239
\end{verbatim}

\textbf{Observations from Sleep Correlations}

\begin{itemize}
\tightlist
\item
  There is a moderate negative correlation between sleep and Sedentary
  Minutes, this suggests that users sleep better when their Sedentary
  Minutes are lower.
\end{itemize}

\includegraphics{Bellabeat_files/figure-latex/Correlations Plot Asleep & Sedentary Minutes-1.pdf}

\paragraph{\texorpdfstring{\textbf{Calorie
Correlations}}{Calorie Correlations}}\label{calorie-correlations}

\begin{verbatim}
##                      Correlation of Calories
## TotalSteps                        0.40630068
## TotalDistance                     0.52121615
## VeryActiveMinutes                 0.61119829
## FairlyActiveMinutes               0.17598776
## LightlyActiveMinutes              0.11376614
## SedentaryMinutes                  0.09865571
## Calories                          1.00000000
## TotalMinutesAsleep               -0.03169899
## TotalTimeInBed                   -0.13480458
\end{verbatim}

\textbf{Observations from Calories Correlations}

\begin{itemize}
\tightlist
\item
  There is a strong positive correlation between Total Steps, Distance,
  Active Minutes and Calories burned; as expected.
\item
  Total Distance and Total Steps both have a positive correlation with
  Calories burned; distance having a slightly stronger correlation
\end{itemize}

\includegraphics{Bellabeat_files/figure-latex/Correlations Charts Calories & Steps vs Distance -1.pdf}

\paragraph{\texorpdfstring{\textbf{Most Active Times}\\
}{Most Active Times }}\label{most-active-times}

\textbf{User activity has a correlation to the time of day and day of
the week}

\includegraphics{Bellabeat_files/figure-latex/Hourly Intensity-1.pdf}

\textbf{Active Hours}

\begin{itemize}
\tightlist
\item
  Very Active 08:00 -20:00
\item
  Mid Active 06:00 - 08:00 / 20:00 -22:00
\item
  Low Active 23:00 - 6:00
\end{itemize}

\includegraphics{Bellabeat_files/figure-latex/Daily Plot-1.pdf}

\textbf{Active Days}

\begin{itemize}
\tightlist
\item
  Users are most active on Saturday, followed by Monday and Tuesday
  respectively
\item
  Mid-week (Wednesday, Thursday, Friday) has slightly lower activity
\item
  Sunday is the lowest activity day
\end{itemize}

\subsubsection{\texorpdfstring{\textbf{6. Act}}{6. Act}}\label{act}

\paragraph{\texorpdfstring{\textbf{Findings and
Recommendations}}{Findings and Recommendations}}\label{findings-and-recommendations}

\textbf{Observations}

\begin{itemize}
\tightlist
\item
  Users average a daily distance of 6.27 miles and 8515, however as the
  standard deviation is 3 miles and 4157 steps there is a significant
  variation between the activities of the users
\item
  Users spend the most time in low impact activity and only 40\% are
  meeting or exceeding the recommended 10K daily steps
\item
  Users with higher sedentary time have lower time spent asleep
\item
  Users are most active on Saturdays, Mondays and Tuesdays with mid day
  and evening hours having the highest activity
\end{itemize}

\textbf{Recommendations}

Functionality:

\begin{itemize}
\item
  Gamification: Incorporating both individual and competitive goals,
  rewards, streaks, and achievements can help increase user engagement
  and activity.
\item
  Recommendations for active lifestyle and quality sleep strategies can
  add additional value for the user
\item
  Social Networking: Providing in-app chat ability and user interaction
  can promote exercise habits and enhance user engagement. Have a
  community provides accountability and motivation for the users to be
  active.
\item
  Alerts:

  \begin{itemize}
  \tightlist
  \item
    Give users the ability to set alerts and reminders

    \begin{itemize}
    \tightlist
    \item
      Daily exercise and sleep reminders
    \item
      Step count notifications through out the day
    \item
      Extended period sedentary time warning for a break reminder and to
      encourage activity
    \end{itemize}
  \end{itemize}
\end{itemize}

\textbf{Data}

\begin{itemize}
\tightlist
\item
  The data analysis was done on a very limited and dated data set -
  Additional analysis with Bellabeat's tracking data recommended
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\end{document}
